name: Run automation Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ui-tests:
    name: Cypress UI tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '23'  

      - name: Install dependencies
        run: npm install

      - name: Run ui-tests
        run: npm run testUi

      - name: Merge json reports
        run: npm run report:merge

      - name: Convert json to HTML
        run: npm run report:generate

      - name: Zip HTML Report
        run: |
          mkdir -p artifacts
          zip -r artifacts/ui-tests-report.zip ui-tests/reports/html

      - name: Upload UI-tests Report
        uses: actions/upload-artifact@v4
        with:
            name: ui-tests-report
            path: artifacts/ui-tests-report.zip

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ui-tests/screenshots

  api-tests:
    name: Postman API tests using Newman 
    runs-on: ubuntu-latest
    # needs: ui-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run Newman API tests with report via npm script
        run: npm run testApiWithReport

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v4
        with:
          name: API-tests-report
          path: api-tests/reports/api-test-report.html 

  k6-test:
    name: k6 performance test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo gpg -k || true
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6 -y

      - name: Run k6 performance test
        run: |
          npm run testLoadCI

      - name: Save test output
        uses: actions/upload-artifact@v4
        with:
          name: Perf-tests-output
          path: performance-tests/test_summary.json

