name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '23'  

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload test artifacts
        if: failure() && env.UPLOAD_ARTIFACTS
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ui-tests/screenshots
